# -*- coding: utf-8 -*-
"""Nomi T-I.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M0BbgGK1t1PmN_NJkzwTratfUJz4hHrr
"""

 !pip install diffusers transformers accelerate scipy safetensors

from huggingface_hub import login

login("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")

import torch
from diffusers import StableDiffusionXLPipeline

pipe = StableDiffusionXLPipeline.from_pretrained(
    "stabilityai/stable-diffusion-xl-base-1.0",
    torch_dtype=torch.float16,
    use_safetensors=True,
).to("cuda")

prompt = "Create an image of a porsche 911 in black color with a mansion in background with a black horse standing beside the car in a foggy weather"
image = pipe(prompt).images[0]
display(image)

image.save("output.png")
